### ISSUE TITLE
Pimms immutable error

### ISSUE THREAD

**Issue by ezgirmak** [noahbenson/neuropythy#10]
Hi Noah,

I recently pulled neuropythy and reinstalled it before running analyses. When I tried to set path to an HCP subject I got the following error: 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-4420f539bfb7> in <module>
----> 1 sub = ny.hcp_subject(412528)

~/.conda/envs/py3/lib/python3.6/site-packages/neuropythy-0.9.4-py3.6.egg/neuropythy/hcp/core.py in subject(sid, subjects_path, meta_data, default_alignment)
    267     fdir = os.path.abspath(os.path.join(pth, fnm))
    268     if fdir in subject._cache: return subject._cache[fdir]
--> 269     sub = Subject(sid, fdir, meta_data=meta_data, default_alignment=default_alignment).persist()
    270     if isinstance(sub, Subject): subject._cache[fdir] = sub
    271     return sub

~/.conda/envs/py3/lib/python3.6/site-packages/pimms/immutable.py in _init_wrapper(imm, *args, **kwargs)
    726     def _init_wrapper(imm, *args, **kwargs):
    727         # call the init normally...
--> 728         initfn(imm, *args, **kwargs)
    729         # If we're still initializing after running the constructor, we need to switch to
    730         # transient

~/.conda/envs/py3/lib/python3.6/site-packages/neuropythy-0.9.4-py3.6.egg/neuropythy/hcp/core.py in __init__(self, sid, path, meta_data, default_alignment)
     39         self.subject_id = sid
     40         self.name = name
---> 41         self.path = path
     42         self.default_alignment = default_alignment
     43         self.meta_data = meta_data

~/.conda/envs/py3/lib/python3.6/site-packages/pimms/immutable.py in _imm_setattr(self, name, value)
    209         return _imm_trans_setattr(self, name, value)
    210     else:
--> 211         return _imm_init_setattr(self, name, value)
    212 def _imm_trans_delattr(self, name):
    213     '''

~/.conda/envs/py3/lib/python3.6/site-packages/pimms/immutable.py in _imm_init_setattr(self, name, value)
    163     else:
    164         raise TypeError(
--> 165             'Attempt to change non-parameter \'%s\' of initializing immutable' % name)
    166 def _imm_trans_setattr(self, name, value):
    167     '''

TypeError: Attempt to change non-parameter 'path' of initializing immutable
`

The versions for pimms and neuropythy are as follows:

neuropythy version : '0.9.4'
pimms version : '0.3.6'

I went back and reinstalled neuropythy from a version committed in May 27 and now the code works but I wanted to let you know of this error. 

Thanks,
Ezgi

**Comment by noahbenson** [comment]
Ha, I am literally rewriting some of the HCP auto-loading stuff right now (major cleanup, not much interface change) and left the repo code in a dirty state in order to move from work to laptop. I was just hoping nobody would notice. ;-)

This will be fixed in the day and I will close the issue then; for now just use the previous version.

Among other things, the code rewrite fixed the current issue that you can't add your own properties/data to HCP subjects in neuropythy.

**Comment by noahbenson** [comment]
Okay I just pushed the changes that should fix this (v0.9.5), so I'm going to go ahead and close this issue for now. That said, the updates are fairly extensive, and I've likely introduces some bugs that I haven't found yet. Let me know if you come across related issues!

For the most part, the API/interface has not changed; you can still get HCP subjects via `ny.hcp_subject(100610)`; retinotopy subjects will have retinotopic mapping parameters included (though there are now more of them and the two different split-half versions are included with the subject). One small change is that the `ny.hcp.download()` function is now part of the 'hcp' dataset, so you would instead use `ny.data['hcp'].download()`.
