### ISSUE TITLE
Question about ny.hcp.download

### ISSUE THREAD

**Issue by syoh** [noahbenson/neuropythy#14]
Thanks for this package!

I am having trouble getting downloading to work. I used docker-compose to start a notebook, and the following is the output:

![Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/1441512/63373872-8b5c1580-c33d-11e9-857c-36ec12f6cef8.png)

What am I missing? Thanks!

(BTW, AWS S3 credential is a non-functional one)

**Comment by noahbenson** [comment]
Ahh, I believe that what happened is this: I moved the `download` function when I rearranged and cleaned-up a bunch of the HCP code recently and forgot import a copy back into the `neuropythy.hcp` module. For now you can use `ny.data['hcp'].download()` instead--though note that I haven't tested this version very much. Let me know if you encounter bugs. Auto-downloading of the subjects should also work: if you just start interacting with subject objects their data should get downloaded.

I'll add `download` back into the `hcp` module in a future version.

**Comment by syoh** [comment]
Thanks for the quick response! I will try it

**Comment by noahbenson** [comment]
FYI this has now been added into the current version and seems to work in my tests.
