### ISSUE TITLE
docker does not run all requested retinotopy atlases

### ISSUE THREAD

**Issue by irisgroen** [noahbenson/neuropythy#27]
Hi Noah! One issue I have when computing the retinotopy atlases for a subject's freesurfer directory using the docker, is that it doesn’t run all the requested atlases at once; it seems to randomly stop after running for 1 or 2 minutes or so. For example, when I request the wang atlases, it will run both mplbl and fplbl for rh but only one of them for lh (see example command and output below).

When I run the same command again it will sometimes start with rh, so if I just keep running it often enough I do end up with all of them, but it's unclear why it's not just doing all of the requested ones in one go. Also when I request multiple atlases (using e.g. --atlases=wang15,benson14,glasser16) it will just (seemingly randomly?) pick a few to run but not 'finish' them all. Do you have any idea what might be going on? As far as I know I’m running it the right way, with the latest docker version of neuropythy. It seem to just time out for some reason, but without a warning or error message. 

Thanks!! Iris

Command:

`docker run --rm -it -v ${bidsFolder}/derivatives/freesurfer:/subjects/ nben/neuropythy atlas sub-${subjectID} --atlases=wang15 --verbose\`

```
Using default tag: latest
latest: Pulling from nben/neuropythy
Digest: sha256:17baa9159f9788d63c72ba417fedd94daa3e9e772509bda7a0cd6afddf5214c2
Status: Image is up to date for nben/neuropythy:latest
docker.io/nben/neuropythy:latest
  * Using FreeSurfer subject: /subjects/sub-p01
  * Using Atlas subject: /data/required_subjects/fsaverage
  * Preparing Hemispheres...
  * Preparing Atlases...
      * Atlas: wang15, Version: (1, 0)
  * Preparing Filemap...
  * Extracting Files...
      * /subjects/sub-p01/surf/rh.wang15_mplbl.mgz
      * /subjects/sub-p01/surf/rh.wang15_fplbl.mgz
      * /subjects/sub-p01/surf/lh.wang15_mplbl.mgz
```

**Comment by noahbenson** [comment]
Hi Iris! This usually happens because the Docker runs out of memory. You should be able to edit your docker settings (on mac, there's an option on the docker desktop—click the whale icon in the menu bar) to tell it how much RAM it's allowed to use.
Given that there's no error message, this is probably the issue, but if not, you may need to send me your subject folder to debug as I'm not sure what else it might be!

**Comment by irisgroen** [comment]
Ah indeed it was just the memory! I'll make a note in my run file so I don't forget next time :) Thanks!!
