### ISSUE TITLE
Atlas command only extracts wang2015_ips atlas?

### ISSUE THREAD

**Issue by Gilles86** [noahbenson/neuropythy#29]
Hallo Noah,

Thanks for the great package.

For a project I used neuropythy to get the wang2015 in individual space. For all old subjects I had a `lh.wang15_fplbl.mgz` and `lh.wang15_mplbl.mgz`-file. However, when I run the command
`docker run -ti --rm -v /data/ds-risk/derivatives/freesurfer:/subjects nben/neuropythy:0.10.5 atlas --verbose sub-30 --atlases wang15` (so I use the old version; same issue with `latest`) now, it only extracts the `rh.wang15_ips.mgz` and `lh.wang15_ips.mgz`-files. The other atlas files are lacking.

I've seen the thread by Iris Groen (https://github.com/noahbenson/neuropythy/issues/27). I doubt this memory issue is my issue. I have 64GB on my server and no Docker limit on resources. Shouldn't that be enough?

Btw: I wanted to run this on my Macbook, but I can't because it's a arm64-architecture. Any plans to allow fort hos in the near future?

**Comment by noahbenson** [comment]
Hi there,
Whichever version you are using (I only really support `latest` currently), it should extract `lh.wang15_mplbl.mgz` and `lh.wang15_fplbl.mgz` for the maximum and full probability atlases. `lh.wang15_ips.mgz` is not a file managed by neuropythy, and I'm not sure where it's coming from. If I had to guess, you have files like `lh.wang15_ips.mgz` in the `fsaverage/surf` directory of your subjects directory, and neuropythy thinks you are trying to use them instead of its copies of the atlases. If this is the case, it should be fixed by running the command as:
```bash
docker run -ti --rm -v /data/ds-risk/derivatives/freesurfer/sub-30:/subjects/sub-30 nben/neuropythy:0.10.5 atlas --verbose sub-30 --atlases wang15
```

**Comment by noahbenson** [comment]
Regarding the macbook architecture, that's entirely outside my control unfortunately—it's an issue with Apple and Docker, not with my code or library!

**Comment by noahbenson** [comment]
Actually, I take that back—I'm seeing versions of docker available for both old and new apple chips, so I'm not even sure what isn't working (or why anything wouldn't work) for you on the arm64 macs.

**Comment by Gilles86** [comment]
> Actually, I take that back—I'm seeing versions of docker available for both old and new apple chips, so I'm not even sure what isn't working (or why anything wouldn't work) for you on the arm64 macs.

Ah, as far as I understand docker images can have different architectures. E.g., when you go to the Neuropythy Docker release:
https://hub.docker.com/r/nben/neuropythy/tags

They all have a `linux/amd64`-tag. I guess you can build them again for other architectures. It's fine for me like this. I still have a Linux box on the campus ;).

Have a nice new year!

**Comment by noahbenson** [comment]
Unless something has changed about docker that I'm not aware of, those tags should be for the image's operating system. The whole point of docker is that you don't need to have the same OS and libraries installed as the person who made the image—the docker system handles the virtual machines of the images for you. In fact, all the neuropythy docker images are running linux internally, but you can run the image on linux/mac/windows.
Have you tried running the docker on an arm64 Mac? If you are getting a specific error, we can try to debug that, but I just tested them on a mac with an M1 chip, and everything worked fine.
