### ISSUE TITLE
NumPy >1.20 deprecation incompatibility

### ISSUE THREAD

**Issue by hharveygit** [noahbenson/neuropythy#30]
Hi Noah,

I reinstalled neuropythy today via `pip install neuropythy`, using Python v3.8.16. The latest version of NumPy (1.24) was installed as dependency.
When I tried to calculate Wang and Benson atlases: `python -m neuropythy atlas sub_name`, the code exited with:

`AttributeError: module 'numpy' has no attribute 'int'.
'np.int' was a deprecated alias for the builtin 'int'. To avoid this error in existing code, use 'int' by itself. Doing this will not modify any behavior and is safe. When replacing 'np.int', you may wish to use e.g. 'np.int64' or 'np.int32' to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20;`

I worked around this issue by rolling back NumPy in my venv to 1.19.5.

Posting in case others are experiencing this or if I'm doing something obviously wrong in installation.
Thanks! -Harvey

**Comment by noahbenson** [comment]
Hi Harvey! Thanks so much for the bug report—I am just back from vacation so just seeing this, but I should be able to fix it (and push a new neuropythy version) within a day or so. The bug is straightforward.
I'll post here when it's fixed.
