### ISSUE TITLE
Typo in `mesh.from_image`

### ISSUE THREAD

**Issue by billbrod** [noahbenson/neuropythy#7]
There's an inconsistency in the name of one of the arguments for `Mesh.from_image`: [the method](https://github.com/noahbenson/neuropythy/blob/master/neuropythy/geometry/mesh.py#L1657) uses `weights`, while the call to it in [Cortex.from_image](https://github.com/noahbenson/neuropythy/blob/master/neuropythy/mri/core.py#L737) uses `weight`.

`weight` is used pretty consistently throughout `mri/core.py`, for all of its `from_image` methods, but I'm not sure about elsewhere.

This prevents `subject.image_to_cortex` from running successfully, raising the following exception: `TypeError: from_image() got unexpected keyword argument 'weight'`

**Comment by noahbenson** [comment]
Thanks for the fix!
