### ISSUE TITLE
potential mismatch between angle format in wiki and predict_retinotopy

### ISSUE THREAD

**Issue by psadil** [noahbenson/neuropythy#9]
The [wiki](https://github.com/noahbenson/neuropythy/wiki/Retinotopy#prediction) currently states that `predict_retinotopy` and `benson14_retinotopy` will output angles such that 

> The polar angle is reported in degrees of rotation around the visual field in the clockwise direction with 0° indicating the upper vertical meridian. So +90° is the right horizontal meridian, -90° is the left horizontal meridian, and ±180° is the lower vertical meridian.

Should that be accurate? Having just run `benson14_retinotopy` with docker (ID 19a5e7a7e40c), it seems like the angles I'm getting are positive for both left and right hemispheres.

```
docker run --rm -it -v $PWD/derivatives/freesurfer:/subjects \
nben/neuropythy:latest benson14_retinotopy --verbose --vol-format=nii.gz sub-02
``` 

but then

```
from nibabel import freesurfer
lh = freesurfer.read_morph_data('derivatives/freesurfer/sub-02/surf/lh.benson14_angle')
rh = freesurfer.read_morph_data('derivatives/freesurfer/sub-02/surf/rh.benson14_angle')

lh.min()
# Out: 0.0
rh.min()
# Out: 0.0
```
Is the wiki wrong?

thanks

**Comment by noahbenson** [comment]
That's correct--the wiki is wrong; though the next version of neuropythy will have an optional argument `sym_angle` that can be set to False to get the non-symmetric map. The current behavior is the convention from the original paper in which we compared RH and LH; though the newer versions of the template aren't defined on fsaverage_sym anymore, so this is no longer really makes sense. Anyway, I updated the wiki to reflect the actual behavior; thanks for the catch!

**Comment by psadil** [comment]
Sorry to revive a closed issue, but could you clarify the angle data that's expected by `register_retinotopy`? The [wiki](https://github.com/noahbenson/neuropythy/wiki/Retinotopy#inference) says that the input RH angles ought to be negative. However, the `--no-invert-rh-angle` flag says

> Note that both the standard and the fsaverage_sym model (see --model-sym option) encode the polar angle values as ranging from 0 degrees (upper vertical meridian) to 180 degrees (lower vertical meridian)

Based on the name of the flag, I'd assume that when set to the non-default value of false (`--no-invert-rh-angle=False`), the RH data are left as is. But, this explanation of the flag seems to say that the model (what I understand to be the prior) encodes all angles as positive, from 0-180. 

Is it the case that if the RH angles are negative, should the `--no-invert-rh-angle` flag be left to the default value of true (which I think the wiki suggests)? Or, if the RH data are negative, should `--no-invert-rh-angle=False`?

Thanks again

**Comment by psadil** [comment]
nevermind, I think I understand. `--no-invert-rh-angle` is just a flag, not an argument to set (it can't be set `=False`). In that case, all of the instructions are clear.

**Comment by noahbenson** [comment]
Sorry have been traveling this last week.
I see the confusion--will update the documentation to make it clearer. Thanks!
